services:
  urundb:
    image: postgres
    container_name: urundb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=urundb;Port=5432;Database=CatalogDb;User Id=postgres;Password=pass;Include Error Detail=true
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=682862Ask
    depends_on:
      - urundb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - /Users/ilkerciblak/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro
  sepetdb:
    image: postgres
    container_name: sepetdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgres/data
    
volumes:
  postgres_catalog:
  postgres_basket:


# Use postgres/example user/password credentials
#version: '3.9'

#services:
#
#  db:
#    image: postgres
#    restart: always
#    # set shared memory limit when using docker-compose
#    shm_size: 128mb
#    # or set shared memory limit when deploy via swarm stack
#    #volumes:
#    #  - type: tmpfs
#    #    target: /dev/shm
#    #    tmpfs:
#    #      size: 134217728 # 128*2^20 bytes = 128Mb
#    environment:
#      POSTGRES_PASSWORD: example
#
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

