# This is a generated file. Not intended for manual editing.
services:
  discount.grpc:
    build:
      context: "/Users/ilkerciblak/Development/edu/dotnet-educational/DukkanMicroserviceDemo/dukkan-microservices"
      dockerfile: "Services/Discount/Discount.gRPC/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Discount.gRPC.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "discount.grpc:dev"
    ports: []
    volumes:
    - "/Users/ilkerciblak/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/ilkerciblak/Development/edu/dotnet-educational/DukkanMicroserviceDemo/dukkan-microservices/Services/Discount/Discount.gRPC:/app:rw"
    - "/Users/ilkerciblak/Development/edu/dotnet-educational/DukkanMicroserviceDemo/dukkan-microservices:/src:rw"
    working_dir: "/app"
